"""Tests for the SSE event stream + runtime polling config (Task 07).

The SSE wire format itself is well-tested by sse-starlette upstream. Here we
focus on:
  * the subscription mechanism (cross-thread event delivery)
  * the polling-config route and persistence
  * route presence and shape
"""
from __future__ import annotations

import asyncio
import json
from pathlib import Path

import pytest
from fastapi.testclient import TestClient

from harness.server import create_app
from harness.server_docs import SESSION_HEADER
from harness.sessions import Session


ROM_PATH = Path(__file__).resolve().parents[2] / "pokered-fork" / "pokered.gbc"
ROM_AVAILABLE = ROM_PATH.exists()

pytestmark = pytest.mark.skipif(
    not ROM_AVAILABLE,
    reason=f"instrumented ROM not built: {ROM_PATH}.",
)


@pytest.fixture
def client(tmp_path):
    app = create_app(base_dir=tmp_path / "sessions", rom_path=str(ROM_PATH))
    with TestClient(app) as c:
        yield c


@pytest.fixture
def session_id(client):
    r = client.post("/sessions/start", json={"name": "stream-test", "snapshot_interval_frames": 0})
    return r.json()["session_id"]


# ---------------------------------------------------------------------------
# Polling config
# ---------------------------------------------------------------------------

def test_snapshots_poll_get_current(client, session_id):
    r = client.post("/snapshots/poll", headers={SESSION_HEADER: session_id}, json={})
    assert r.status_code == 200
    assert r.json()["interval_frames"] == 0


def test_snapshots_poll_set_persists(client, session_id):
    r = client.post("/snapshots/poll", headers={SESSION_HEADER: session_id},
                    json={"interval_frames": 30})
    assert r.status_code == 200
    assert r.json() == {"interval_frames": 30, "previous": 0}

    # Verify meta.json was updated on disk
    registry = client.app.state.registry
    folder = registry.base_dir / session_id
    meta = json.loads((folder / "meta.json").read_text())
    assert meta["snapshot_interval_frames"] == 30

    # And via the API
    r = client.post("/snapshots/poll", headers={SESSION_HEADER: session_id}, json={})
    assert r.json()["interval_frames"] == 30


def test_snapshots_poll_validates_negative(client, session_id):
    r = client.post("/snapshots/poll", headers={SESSION_HEADER: session_id},
                    json={"interval_frames": -1})
    assert r.status_code == 400


# ---------------------------------------------------------------------------
# SSE route is registered and returns the expected content type
# ---------------------------------------------------------------------------

def test_events_stream_route_present(client):
    # GET returns docs (not the stream itself). Default is markdown; pass
    # ?format=json for the structured doc dict.
    r = client.get("/events/stream")
    assert r.status_code == 200
    assert r.headers["content-type"].startswith("text/markdown")
    assert "/events/stream" in r.text

    r = client.get("/events/stream?format=json")
    doc = r.json()
    assert doc["method"] == "POST"
    assert doc["path"] == "/events/stream"


# ---------------------------------------------------------------------------
# Subscription mechanism — bypass HTTP, exercise the Session class directly
# ---------------------------------------------------------------------------

def _run_async(coro):
    """Run an async coroutine to completion in a fresh loop."""
    return asyncio.run(coro)


def test_subscribe_delivers_press_events(tmp_path):
    """The subscriber queue should receive events generated by press_button.

    press_button is called synchronously from inside the test; the queue
    is asyncio.Queue but the publisher uses call_soon_threadsafe — so we
    run the whole test in an async loop with a separate thread for the press.
    """
    base_dir = tmp_path / "sessions"
    session = Session.create(base_dir, ROM_PATH, snapshot_interval_frames=0)
    try:
        async def driver():
            queue = session.subscribe_events()
            try:
                # Run the press in a thread so the loop stays alive to receive
                # publish notifications via call_soon_threadsafe.
                def press_work():
                    # Boot to a state where text_display fires
                    session.wait(900)
                    return session.press_button("start", hold_frames=10, release_frames=80)

                events = await asyncio.to_thread(press_work)
                # The publisher used call_soon_threadsafe; pump the loop briefly
                # so scheduled put_nowait() calls actually land in the queue.
                await asyncio.sleep(0.1)
                # Drain the queue
                drained: list = []
                while not queue.empty():
                    drained.append(await queue.get())
                return events, drained
            finally:
                session.unsubscribe_events(queue)

        events, drained = _run_async(driver())
        # The subscriber received events from BOTH wait(900) and the press;
        # `events` only contains the press's return value. Both should be
        # non-empty.
        assert len(drained) > 0
        # The press's events should be a subset of what the subscriber saw.
        event_ids = {e.id for e in events}
        drained_ids = {e.id for e in drained}
        if event_ids:
            assert event_ids.issubset(drained_ids), \
                f"press events {event_ids} not seen by subscriber {drained_ids}"
    finally:
        session.end()


def test_unsubscribe_stops_delivery(tmp_path):
    """After unsubscribe, no new events should appear in the queue."""
    base_dir = tmp_path / "sessions"
    session = Session.create(base_dir, ROM_PATH, snapshot_interval_frames=0)
    try:
        async def driver():
            queue = session.subscribe_events()
            session.unsubscribe_events(queue)
            # Generate events
            await asyncio.to_thread(session.wait, 900)
            await asyncio.sleep(0.05)
            return queue.empty()

        assert _run_async(driver())
    finally:
        session.end()
